### ISSUE TITLE
Add a form after first log in to collect user data

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/global-research-platform#68]
Need: Start a database of users/ contributors.  

There’s a PATCH /me endpoint that takes a json body with the following optional params. 

{
  "name": "",
  "company": "",
  "location": "",
  "picture": ""
}

**Comment by maxohsawa** [comment]
I'll give this issue a go.

**Comment by becca-tiessen** [comment]
same same! I'll give it the old college try

**Comment by becca-tiessen** [comment]
We've run into two blockers, that require a bit more python knowledge than we've got at the moment; so I'll note them here so someone can take a stab at them later!
- we're not sure how to route to this page only if it's a user's first sign in, so we've made the page but aren't directing the user there yet
- also not sure how to get the user's profile picture URL from the google token so we're able to save it during the patch

Otherwise we'll have a PR up for this today!

**Comment by ssmssam** [comment]
Is this still an issue? I could try picking things up fro mthe Python side if so

**Comment by becca-tiessen** [comment]
I can try to have a PR up this week for our side (needs some cleanup) and then you can take a stab at it for sure!
